### ISSUE TITLE
Two roles with admin in project

### ISSUE THREAD

**Issue by SalahAdDin** [lambdalisue/django-permission#28]
Good Nights, this is a question, not a issue.

I need to do two types of users, and default admin and author user.
An aditional permission for two users, Admin can publish news, author can't.
Author only can created news, and only edit and delect his own news.

A friend say me that for the second restrictions i need per object permissions, but i don't know how do all of this.

Can you help me?

**Comment by Allan-Nava** [comment]
The django-permission and django-guardian can coexist? 
I have the same issue of @SalahAdDin  only the member of a specif group can add the member

**Comment by lambdalisue** [comment]
> The django-permission and django-guardian can coexist?

Yes, if you are careful enough for confliction (e.g. django-guardian say Yes but django-permission say No for permission A or whatever).
So I don't recommend.

> only the member of a specif group can add the member

It sounds you don't need object permission.
Add permissions to a particular `Group`. https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#group-model

**Comment by Allan-Nava** [comment]
> It sounds you don't need object permission.
> Add permissions to a particular Group. 
> https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#group-model

I tried but if I add the permission "can add group member", the user can add a new member only in the respective group.
Do you think is possible?

**Comment by lambdalisue** [comment]
> I tried but if I add the permission "can add group member", the user can add a new member only in the respective group.
Do you think is possible?

No idea while I don't know what you've tried or what you want to do.

**Comment by Allan-Nava** [comment]
I need to have a permission, that let the users of a specific group to add,
delete or remove only for the specific group.

Now is more clear?
Sorry for my english

2017-11-17 18:35 GMT+01:00 Alisue <notifications@github.com>:

**Comment by lambdalisue** [comment]
Sorry for late. Do you have code?

**Comment by Allan-Nava** [comment]
@lambdalisue No problem, I have fixed with [groups_manager](https://github.com/vittoriozamboni/django-groups-manager) and [django-guardian](https://github.com/django-guardian/django-guardian).

Now i have a bug in admin panel for this [issue](https://github.com/django-guardian/django-guardian/issues/536)

**Comment by lambdalisue** [comment]
ic. wish you could solve the problem 👍

**Comment by Allan-Nava** [comment]
Thank you for support! I try to solve the problem 👍
