### ISSUE TITLE
May be permission.autodiscover() should have some kind of fail-fast mechanism

### ISSUE THREAD

**Issue by kirthiprakash** [lambdalisue/django-permission#32]
Hi,

Well, this is not an issue with django-permission, but more of a workflow correction.
Everything was working fine at my local instance but when I pushed to staging, the custom permission logic was never getting invoked. I made sure autodiscover() is getting called before checking for permission but still it wasn't working. Later realized I had forgotten to set the authentication backend in the settings file (which usually stays out of repo).

Can there be a mechanism, where in, the autodiscover() should fail if the permission app is not declared in INSTALLED_APPS or if its not declared in the authentication backends?

**Comment by lambdalisue** [comment]
> Can there be a mechanism, where in, the autodiscover() should fail if the permission app is not declared in INSTALLED_APPS or if its not declared in the authentication backends?

It should be fail if the `django-permission` is declared in `INSTALLED_APPS` **without** declearion of authentication backend, right?

Hum... It is actually quite easy to add the mechanism.
In fact, django-permission previously had such kind of validation at three years ago (https://github.com/lambdalisue/django-permission/blob/3c91baeceab27a4e33e283e1f3970d03196aee7b/permission/__init__.py#L21-L34)

I removed that while it was a bit annoying when I just want to use templatetags or decorators provided in django-permission. But now, django-permission get really stable and I don't think people would use django-permission without it's authentication backend.... 

I feel like I should re-raise the code back to prevent human-error but let me think about this.

**Comment by lambdalisue** [comment]
I add the mechanism. https://github.com/lambdalisue/django-permission/commit/b52c45cdf27a474e2dada0504c8331cf803901b6
