### ISSUE TITLE
Custom permission logics documentation

### ISSUE THREAD

**Issue by stevelacey** [lambdalisue/django-permission#33]
I am really struggling to understand how I am meant to use custom permission logics, I am pretty sure I am 99% of the way there, and that they're what I want, but the documentation is so sparse it's really putting me off, but yours appears to be the only library that seems to cater for this requirement.

My current error is `django.contrib.auth.models.DoesNotExist` simply because the row doesn't exist in the `auth_permission` table.

Now, I have no desire to maintain database records to describe my permissions – but I'd be happy to create these if necessary, but what I don't understand is what or where should be doing that, or more importantly, what binds permissions to logics, how does it know which logic class to run based on the permission being checked, and if it's multiple or all of them, what happens if one logic says yes and another says no? Unanimous voting? ¯\_(ツ)_/¯

**Comment by stevelacey** [comment]
Is it to do with app prefixes, if the permission has an app prefix `yourapp.something_or_other` should it run through the permission logic classes on that app rather than hit the db? Again, still don't get how it correlates which logic to use... but still, just thinking out loud / trying to describe the conclusions I am drawing based on docs zero.

**Comment by stevelacey** [comment]
So, permissions are bound to models, and a model can only have one permission logic? I think that may have been the salient piece I was missing.

**Comment by stevelacey** [comment]
Or do permissions bound to a user or their group(s) via db override class-based logics?

**Comment by stevelacey** [comment]
No, it appears, if a custom logic is set for a model then it is always ran and the db described permissions joint to the user/group are ignored?

**Comment by lambdalisue** [comment]
Ok. I'm not really sure that I understand your question correctly so let me know I'm in out of your question.

> Now, I have no desire to maintain database records to describe my permissions – but I'd be happy to create these if necessary

A database is required while django's default permission system use database and django-permission use an instance of `django.contrib.auth.model.Permission`, mean that you have to make it possible to create an instance of that.
django-permission is non database based permission system but it is built on a django's default permission system thus minimum database for that permission system is required (`django.contrib.auth`).

> what binds permissions to logics, how does it know which logic class to run based on the permission being checked

A django permission (`django.contrib.auth.models.Permission`) instance is connected to a model instance. It is a default behavior of **django** and it is not related to django-permission.
Based on this default mechanism, **django-permission** use this connection to find permissions which are connected to a specified model (https://github.com/lambdalisue/django-permission/blob/master/src/permission/utils/permissions.py#L113). Thus if you specify a permission, django-permission automatically iterate permission logics bound to a particular model (internally, a model is connected a handler and a handler call all permission logics: https://github.com/lambdalisue/django-permission/blob/master/src/permission/handlers.py#L217).

> and if it's multiple or all of them, what happens if one logic says yes and another says no? Unanimous voting? ¯\_(ツ)_/¯

In general, **any django permission system**, include django-permission, prefer `True`, mean that if one of a permission logic (or backends of other permission system like `django.contrib.auth.backends.ModelBackend`) return `True`, *django* treat the user have the permission.

> So, a permission is bound to a single model, like normal, and a model can only have one permission logic? I think that may have been the salient piece I was missing.

No. Multiple permission logics can be specified to a single model, even mutliple models.

> Or do permissions bound to a user or their group(s) via db override class-based logics?

No. permissin logic bound to a model.

> No, it appears, if a custom logic is set for a model then it is always ran and the db described permissions joint to the user/group are ignored?

I don't really get what you ment in this sentence.

**Comment by lambdalisue** [comment]
If you show me your source code, I think I can help you to solve your problem more correctly. Or if you need any real example, take a look the followings (several comments are written in Japanese but I'm sure that you can understand what they do from the source code).

- A role based permission logic (A custom user model have `role` field)
  https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/core/personas/perms.py
- Complex permission logic for an event model which have a deadline or attendee restrictions
  https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/apps/events/perms.py
- Complex permission logic for a project which have publish status (like draft, internal, public)
  https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/apps/projects/perms.py

**Comment by stevelacey** [comment]
I appreciate the time you've taken here thanks.

I am pretty sure I've wrapped my head around it, I was just leaving the nonsensical comments as a way of seeing the thought process I went through to get to this point.

# Affirmative approach

I think it's worth outlining how your library takes the **affirmative** approach, even if other Django permissions tend to do it the same way, just to make it clear – personally, I am mapping your approach to my Symfony2 understanding described at http://symfony.com/doc/current/components/security/authorization.html#access-decision-manager

> affirmative (default)
> grant access as soon as any voter returns an affirmative response;

One for the docs?

--

So, based on:

> Multiple permission logics can be specified to a single model, even multiple models.

All custom logics I attach to a model will be ran, and as long as at least one returns `True`, the user is allowed the permission, otherwise they are not, and the order in which they're ran should be irrelevant. Yes?

# Custom logic vs db values

> No, it appears, if a custom logic is set for a model then it is always ran and the db described permissions joint to the user/group are ignored?

What I was asking here is whether the custom logic negates any values in the `user_permissions` table – but based on what you've described "prefer `True`", that as long as either a custom logic returns `True`, or a user is bound to a permission via `user_group_permissions` or `user_permissions`, that as long as one of them is `True`, they'll be granted that permission?

**Comment by lambdalisue** [comment]
> I think it's worth outlining how your library takes the affirmative approach, even if other Django permissions tend to do it the same way, just to make it clear

Agree. But it was(is) difficult to explain the behavior in ENGLISH for me.... I even didn't know the word *affirmative*. If you don't mind, could you add the document about it into README.md?

> All custom logics I attach to a model will be ran, and as long as at least one returns True, the user is allowed the permission, otherwise they are not, and the order in which they're ran should be irrelevant. Yes?

Yes. As soon as one of permission logic return `True`, a permission logic handler (which exists mainly for really really complicated permission handling and user usually don't need to know the presence) return `True` (https://github.com/lambdalisue/django-permission/blob/master/src/permission/handlers.py#L256) and a permission backend return `True` (https://github.com/lambdalisue/django-permission/blob/master/src/permission/backends.py#L71) and finally `django.contrib.auth.model._user_has_perm' return `True` (https://github.com/django/django/blob/master/django/contrib/auth/models.py#L281).

> What I was asking here is whether the custom logic negates any values in the user_permissions table – but based on what you've described "prefer True", that as long as either a custom logic returns True, or a user is bound to a permission via user_group_permissions or user_permissions, that as long as one of them is True, they'll be granted that permission?

Yes. Absolutely.

> And based on what I've seen in my experiments, even if a user is bound to a permission for a model via the db, the custom logics will still run, even if they're already granted by a db relation?

Hum.. It should be NO for non object permission. Based on django's permission system, one of a permission backend return `True`, other permission backend should not be called (https://github.com/django/django/blob/master/django/contrib/auth/models.py#L281).
If you are talking about *object permission*, the django's permission backend always return `False` (https://github.com/django/django/blob/master/django/contrib/auth/backends.py#L68) thus permission logics will be called always (if you don't use other permission plugins).

**Comment by stevelacey** [comment]
Yeah sure, I've still got to actually try and build my thing – but assuming I succeed I'll come back and update the docs once I've wrapped my head around it, no problem, nudge me if I forget.

A voter style system might also be a worthwhile venture if it's something you think could be implemented, my preference for permissions systems is "unanimous" voting – and /all/ that would require is making sure all applicable logics ran all of the time (i.e. didn't stop once one returns `True`) and for there to be the ability to return an "abstain" vote – which could be described by a constant or maybe just `None` – just food for thought, I'll create an issue to describe it further if you think it's something you'd ever be interested in merging.

**Comment by stevelacey** [comment]
@lambdalisue last question for now, what is meant to create the permission records my custom logics expect, do I just create them in migrations, or is there some meaningful way to describe what permissions a logic supports?

**Comment by lambdalisue** [comment]
> A voter style implementation/mode might also be a worthwhile venture if it's something you think could be implemented/are interested in, my preference for permissions systems is "unanimous" voting – and /all/ that would require is making sure all applicable logics run all of the time (i.e. didn't stop once one returns True) and for there to be the ability to return an "abstain" vote – which could be described by a constant or maybe just None – just food for thought, I'll create an issue to describe it further if you think it's something you'd ever be interested in merging.

Hum... Sounds nice. Permission Logics can also be used in that way with simple code modification. However, I'm afraid that it may confuse users while django's permission system is affirmative and I cannot change the behaviour of that, mean that even all Permission Logic return `False` (not `None`), django will give a permission to a user if one of the other permission backends return `True`.

Anyway, feel free to ask questions related to django-permission if you struggle again :-)

**Comment by stevelacey** [comment]
Sounds like a good reason to not bother to me, fair enough!

**Comment by stevelacey** [comment]
@lambdalisue a little offtopic but do you have any recommendations for naming conventions/structure with regards to object permissions – a lot of my requirements are still basic CRUD permissions, but against other objects e.g. "user can create a comment against this article but not all articles"

Now I am using Django 1.6, so I can't trash the default permissions easily – which means I already have a bunch like `add_comment` against the `Comment` mode. Would you recommend setting up an additional `add_comment` permission for the `Article` model, and then using that as an object permission, or does this generally cause pain? Just wondering what the recommended approach is.

**Comment by lambdalisue** [comment]
We usually use `<app_label>.<verb>_<model>` while django follow this rule and that's why project newbies can guess the role of the permission from its name. And if you add any extra `add_comment` for other models (like `blogs.add_comment`), it is quite difficult to find which application use the permission (blogs app does not add a comment, comments app add a comment to a blog), thus I recommend you to follow the django's rule.
While django-permission provide `if` template tag, it is quite natural naming for me (for non native lol).

```html
{% if user has 'comments.add_comment' of obj %}
You can add a comment to the object
{% endif %}
```

**Comment by stevelacey** [comment]
@lambdalisue is the app label actually used for anything? I had assumed it had to correlate to the application to which the model belongs – am I right in thinking it's just semantic?

Are you saying that it makes more sense to put a custom permission logic governing whether a comment can be created against an article in the comments application's perms.py, rather than in the blogs application? e.g.

```py
# /comments/perms.py
...
PERMISSION_LOGICS = (
    ('blogs.Article', ArticleCommentPermissionLogic()), # <--
    ('comments.Comment', CommentPermissionLogic()),
)
```

**Comment by stevelacey** [comment]
Hm, surely the above wouldn't work because it wouldn't find a `django_content_type` of `Article` that has an `app_label` of `comments` ?

**Comment by lambdalisue** [comment]
If you want to control permissions of `comments.Comment`, you should bind a permission logic to a comment model not to an article model even if you want to control a behavior for adding comment on the article model.

For example, if you want to allow guest users to add comments on `blogs.Article` but other models, the following two permission logics can handle the situation.

```python
# /comments/perms.py
class CommentPermissionLogic(PermissionLogic):
    def has_perm(self, user_obj, perm, obj=None):
        if perm not in ('comments.add_comment',):
            # Unknown permission is specified, just ignore
            return False
        # Login users can add a comment
        return user_obj.is_authenticated()

PERMISSION_LOGICS = (
    ('comments.Comment', CommentPermissionLogic()),
)

# /blogs/perms.py
# It is quite blogs.Article specified permission logic thus I would put the code under 'blogs'
class ArticleCommentPermissionLogic(PermissionLogic):
    def has_perm(self, user_obj, perm, obj=None):
        if perm not in ('comments.add_comment',):
            # Unknown permission is specified, just ignore
            return False
        if perm == 'comments.add_comment' and obj is not None:
            # Note:
            #   This is a special case. Usually 'add' permission does not have 'obj' while
            #   'add' permission is non object permission.
            #   To figure out which object is going to be commented, I defined this special case
            #
            #       If a object is specified to 'comments.add_comment' permission, treat that
            #       object as an object which going to be commented.
            #
            #   To establish this, you have to specify an object going to be commented below.
            #   Note that <obj> in the following represent an object going to be commented.
            #
            #       {% If user has 'comments.add_comment' of obj %}
            #
            if isinstance(obj, Article)
                # Everybody can add a comment to blogs.Article
                return True
        return False
PERMISSION_LOGICS = (
    ('comments.Comment', ArticleCommentPermissionLogic()),
)
```

I split the logic into two permission logic but If you want, you can join them together. I just prefer to make systems independent as much as possible (If you split the logic into two logics, at least `comments.Comment` is independent).

**Comment by lambdalisue** [comment]
Note that this is a bit hackish way. add permission should be a non object permission in general thsu the above strategy won't work without django-permission. You'll never be able to do such things in other permission system so make sure your collaborators understand the definition of that special case (django-permission is too flexible. this is an advantage and disadvantage of django-permission)
