### ISSUE TITLE
Python 3 support in django-packages

### ISSUE THREAD

**Issue by joaoponceleao** [lambdalisue/django-permission#43]
You might want to update the django-packages grid and detail page for django-permission. It lists it as not supporting python 3 (had to double check with the repo). That will scare off quite a few people... (couldn't figure out how to update the django-packages pages  myself, otherwise....).

**Comment by lambdalisue** [comment]
Thanks. I think I just forgot to execute `python setup.py register` in current version thus no categories info was in PyPI.

Probably [Django Packages](https://www.djangopackages.com/packages/p/django-permission/) obtain the data from 'Categories' in [PyPI](https://pypi.python.org/pypi/django-permission/). I update PyPI now so it would be fixed hopefully.
