### ISSUE TITLE
users only can have one role.

### ISSUE THREAD

**Issue by SergioDzul** [lambdalisue/django-permission#44]
django 1.8 
when users have more than one role. the method utils.get_roles () generates an error when trying to run the filter (PrincipalRoleRelation.objects.filter) with a string. That marks the following error:

invalid literal for int() with base 10: ','
![error strin in filter](https://cloud.githubusercontent.com/assets/11066914/10442058/a247a6f8-7114-11e5-93aa-9c5c49e2ec06.png)

**Comment by lambdalisue** [comment]
As I said in https://github.com/lambdalisue/django-permission/pull/45, it is a issue of [django-permissions](https://github.com/diefenbach/django-permissions). django-permission does not have any relationship between that.
