### ISSUE TITLE
has_module_perms always return True

### ISSUE THREAD

**Issue by vosi** [lambdalisue/django-permission#59]
even if user doesn't have any perms for the object/module or no permission logic set

**Comment by lambdalisue** [comment]
Could you explain it bit more with procedure for how to reproduce?

**Comment by vosi** [comment]
I'm checking 

``` if self.request.user.has_module_perms(model_cls._meta.app_label): ```

without django-permission - if a user doesn't have any model perms - it returns false (as expected)
with django-permission - even without any logical perms attached to model and no static permissions - it returns true (false expected)

i think it should returm false even with attached (but not matched) logical permissions

**Comment by lambdalisue** [comment]
I could not reproduce your issue on Django 1.8.7

1. Which version of Django do you use
2. Give me a minimum example **project**
