### ISSUE TITLE
Support for View Only permission in Django Admin

### ISSUE THREAD

**Issue by eskhool** [lambdalisue/django-permission#67]
I prefer the approach of this app over django-guardian and django-authority. However is it feasible to add a ViewOnly Permission logic to all model admins? Maybe by inheriting from a common admin or common model/permission?

**Comment by lambdalisue** [comment]
I might mis-understand but do you mean you would like to apply permissions only to admin?
In that case, why do you give permissions to non superuser? Simply remove any permission except for view from everyone while superuser anyway have any permissions

**Comment by eskhool** [comment]
Sorry, I will explain better. The default django auth system has only add, change and delete permissions which are used by django auth appropriately. If one wants to add a view only permission one has to jump through hoops with setting the fields readonly.

I guess the question is does django permission interface with the default django admin app?

**Comment by lambdalisue** [comment]
I still don't really understand the situations but does these link help?

- https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/core/personas/admin/persona.py#L37
- https://github.com/kawazrepos/Kawaz3rd/blob/develop/src/kawaz/core/personas/perms.py#L36
