### ISSUE TITLE
TypeError get_object() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by djbettega** [lambdalisue/django-permission#82]
Hello again,

I am trying to use django-permission in conjunction with another app called [django-viewflow](https://github.com/viewflow/viewflow). When I try the following code on it's own it works as expected, however, when I apply the django-permission decorator it throws the error.

**views.py**

```
from permission.decorators import permission_required

@permission_required('test_app_cbv.change_cbvarticle')
class ArticleCreate(StartFlowMixin, generic.UpdateView):

    model = models.CBVArticle
    form_class = forms.Article_form
    template_name = 'test_app_cbv/edit.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by_id = self.request.user.id
        obj.save()
        return super(ArticleCreate, self).form_valid(form)

    def get_object(self):
        return self.activation.process.article

    def activation_done(self, form):
        article = form.save()
        self.activation.process.article = article
        super(ArticleCreate, self).activation_done(form)

    def dispatch(self, request, **kwargs):
        return super(ArticleCreate, self).dispatch(request, **kwargs)
```

The error details are as follows

get_object() takes 1 positional argument but 2 were given

/home/daniel/Django1.11.4/python3.5.2/lib/python3.5/site-packages/permission/decorators/classbase.py in get_object_from_classbased_instance
 
99. obj = instance.get_object(queryset)

Variable | Value
-- | --
BaseCreateView | <class 'django.views.generic.edit.BaseCreateView'>
args | ()
instance | <test_app_cbv.views.ArticleCreate object at 0x7f8c985fa7b8>
kwargs | {'flow_class': <test_app_cbv.flow.CBVArticleFlow object at 0x7f8c98a11e10>,  'flow_task': <viewflow.flow.nodes.Start object at 0x7f8c98a11710>}
queryset | <QuerySet [<CBVArticle: CBVArticle object>]>
request | <WSGIRequest: GET '/test_cbv/process/start/'>

I have a pretty basic understanding of python - so I am pretty sure that the error is due to something I have not understood. Any suggestions would be great. Thanks in advance!

**Comment by lambdalisue** [comment]
As error message show, the definition of your get_object is wrong.

https://docs.djangoproject.com/en/2.0/ref/class-based-views/mixins-single-object/

**Comment by lambdalisue** [comment]
I'm not familiar with viewflow itself but it seems it changes the basic django mech drastically? Basically get_object is used to determine which object is going to be shown, edit, delete or whatever but it seems not.

Try use get_object(self, *args) instead in your definition (I'm not sure if it works as expect)

**Comment by djbettega** [comment]
Thanks for the help! You were right - correcting the get_object definition solved the problem (now I just need to try to figure out the next error : ) ). Thanks again.
